### ISSUE TITLE
create a custom slot mover

### ISSUE THREAD

**Issue by drfiy** [tixcode/mindfuck#5]
lets imagine an arrow function, that can contain factor of some action
btw, string (>)<-(4) would be equalitenty to string >>>>

or: (++>)<-(2)++  =  ++>++>++

**Comment by drfiy** [comment]
@tixcode

**Comment by tixcode** [comment]
I don't know. I'm know, issue is already closed but it's cool idea, but i can't make that now. **Sorry.**
